### ISSUE TITLE
Descriptions are not accurate when compared with the docs

### ISSUE THREAD

**Issue by maisarissi** [OneDrive/apidoctor#159]
In some cases, like remove a group's member, we are not getting the right description from the [graph docs site](https://learn.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=powershell):

![image](https://user-images.githubusercontent.com/22648831/195678044-5699eb0e-cb04-477c-b840-33e0fc2d31fc.png)

The [methods table](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#methods) in the group resource shows:

![image](https://user-images.githubusercontent.com/22648831/195681438-21590ad6-a6e8-458c-8395-0230a3ef566f.png)

[Powershell reference docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/remove-mggroupmemberbyref?view=graph-powershell-1.0):

![image](https://user-images.githubusercontent.com/22648831/195678166-114d1de1-d5c5-4ba5-8e6f-02e4c447b64f.png)

We can see that this is also happening for Group transitive members. The [docs](https://learn.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=powershell%2Chttp) shows: 

![image](https://user-images.githubusercontent.com/22648831/195679302-d3ee1207-401b-4274-b3d6-d59963ddc397.png)

The [methods table](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#methods) in the resource group shows: 

![image](https://user-images.githubusercontent.com/22648831/195679652-9d9d2310-24c8-488e-a618-4eac4720c1be.png)

And the [PowerShell reference docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggrouptransitivemember?view=graph-powershell-1.0)
![image](https://user-images.githubusercontent.com/22648831/195679437-ca151df0-cb88-44ff-b687-10f7e3a44639.png)

We need to investigate why the right descriptions are not being captured and added into the OpenAPI document.

**Comment by ddyett** [comment]
@millicentachieng for awareness.

**Comment by maisarissi** [comment]
Another example that is not getting the right content from docs: https://learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http and in the PowerShell reference documentation generated based on the OpenAPI description: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplicationtokenlifetimepolicybyref?view=graph-powershell-1.0
