### ISSUE TITLE
Validate cross-repo included links

### ISSUE THREAD

**Issue by millicentachieng** [OneDrive/apidoctor#173]
[Cross-repo includes](https://review.learn.microsoft.com/en-us/help/platform/includes-best-practices?toc=%2Fhelp%2Fplatform%2Ftoc.json&bc=%2Fhelp%2Fplatform%2Fbreadcrumb%2Ftoc.json&branch=main#cross-repo-includes) look like this:

`[!INCLUDE [My included file](~/../friendly_name/folder/include-file.md)]`

API Doctor currently throws an error when such links are encountered.

**Comment by FaithOmbongi** [comment]
Following
