### ISSUE TITLE
Bug: Snippets injection into docs removes entire example section in some cases

### ISSUE THREAD

**Issue by millicentachieng** [OneDrive/apidoctor#177]
Here's the diff from the most recent snippets generation run:
https://github.com/microsoftgraph/microsoft-graph-docs/commit/07d9c965be06aa3d15fe51385018fab12b0f12c1#diff-4ca8caa148322623604dade686fc5aae15f98e32b454d4ac96920074f050c5c8

**Comment by andrueastman** [comment]
It looks like some request blocks may not always have a Response block. 

Example below
https://github.com/microsoftgraph/microsoft-graph-docs/blob/0e74a61c1ee4d1b943259bc439d65e5eb1d17307/concepts/tutorial-applications-basics.md?plain=1#L230

Thus, looking at https://github.com/OneDrive/apidoctor/blob/77f20e5a020d867625a9e7e701d36d607c69029d/ApiDoctor.Console/Program.cs#L2423, we may overflow to the next block section and not finish parsing as we would want to do. This will therefore set the end of the tab block as the end of the next request block.
