### ISSUE TITLE
Support .NET Standard (portable .NET code)

### ISSUE THREAD

**Issue by rgregg** [OneDrive/apidoctor#41]
Today apidoctor targets the .NET Framework in both the console apps and the underlying libraries. It would expand the ability to use apidoctor on other platforms (Mac, Linux) by converting to the .Net Core / .Net Standard world.

I tried to do an initial conversion in my own branch, and found there are a few places where that isn't straight forward. Adding an issue here to see if more progress can be made there.

**Comment by baywet** [comment]
done via #65. closing.
